<!DOCTYPE html>  
<html lang="en">  
    <head>
        <meta charset="UTF-8">
        <title>Goldeneye</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">  
    </head>
    <body>
    	<div class="container">
	    	<h1>Your new email is:</h1>
	    	<h3><a>${email}</a></h3>
	    	<br/>
	    	<form action="/">
	    		<button type="submit" class="btn btn-primary">Return</button>
	    	</form>
    	</div>
 		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>  
    </body>
</html>